config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_for :usuarios
  resources :cannabis
  resources :usuarios
  get 'welcome/index'

  root 'welcome#index'

end

app/models/cannabi.rb
class Cannabi < ActiveRecord::Base
  belongs_to :usuario
  validates :sativa, presence:true
  validates :indica, presence: true
  validates :interior, presence:true
  validates :exterior, presence:true
  scope :recientes, -> {order("created_at desc")} 
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/usuario.rb
class Usuario < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cannabis_controller.rb
class CannabisController < ApplicationController
  before_action :set_cannabi, only: [:show, :edit, :update, :destroy]

  # GET /cannabis
  # GET /cannabis.json
  def index
    @cannabis = Cannabi.recientes.all
  end

  # GET /cannabis/1
  # GET /cannabis/1.json
  def show
  end

  # GET /cannabis/new
  def new
    @cannabi = Cannabi.new
  end

  # GET /cannabis/1/edit
  def edit
  end

  # POST /cannabis
  # POST /cannabis.json
  def create
    @cannabi = Cannabi.new(cannabi_params)

    respond_to do |format|
      if @cannabi.save
        format.html { redirect_to @cannabi, notice: 'Cannabi was successfully created.' }
        format.json { render :show, status: :created, location: @cannabi }
      else
        format.html { render :new }
        format.json { render json: @cannabi.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cannabis/1
  # PATCH/PUT /cannabis/1.json
  def update
    respond_to do |format|
      if @cannabi.update(cannabi_params)
        format.html { redirect_to @cannabi, notice: 'Cannabi was successfully updated.' }
        format.json { render :show, status: :ok, location: @cannabi }
      else
        format.html { render :edit }
        format.json { render json: @cannabi.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cannabis/1
  # DELETE /cannabis/1.json
  def destroy
    @cannabi.destroy
    respond_to do |format|
      format.html { redirect_to cannabis_url, notice: 'Cannabi was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cannabi
      @cannabi = Cannabi.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cannabi_params
      params.require(:cannabi).permit(:sativa, :indica, :interior, :exterior, :usuario_id)
    end
end

app/controllers/usuarios_controller.rb
class UsuariosController < ApplicationController
  before_action :set_usuario, only: [:show, :edit, :update, :destroy]

  # GET /usuarios
  # GET /usuarios.json
  def index
    @usuarios = Usuario.all
  end

  # GET /usuarios/1
  # GET /usuarios/1.json
  def show
  end

  # GET /usuarios/new
  def new
    @usuario = Usuario.new
  end

  # GET /usuarios/1/edit
  def edit
  end

  # POST /usuarios
  # POST /usuarios.json
  def create
    @usuario = Usuario.new(usuario_params)

    respond_to do |format|
      if @usuario.save
        format.html { redirect_to @usuario, notice: 'Usuario was successfully created.' }
        format.json { render :show, status: :created, location: @usuario }
      else
        format.html { render :new }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /usuarios/1
  # PATCH/PUT /usuarios/1.json
  def update
    respond_to do |format|
      if @usuario.update(usuario_params)
        format.html { redirect_to @usuario, notice: 'Usuario was successfully updated.' }
        format.json { render :show, status: :ok, location: @usuario }
      else
        format.html { render :edit }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /usuarios/1
  # DELETE /usuarios/1.json
  def destroy
    @usuario.destroy
    respond_to do |format|
      format.html { redirect_to usuarios_url, notice: 'Usuario was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_usuario
      @usuario = Usuario.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def usuario_params
      params.require(:usuario).permit(:nombre, :apellido, :fechaNacimiento, :comuna)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cannabis_helper.rb
module CannabisHelper
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/cannabis/_form.html.erb
<%= form_for(@cannabi) do |f| %>
  <% if @cannabi.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cannabi.errors.count, "error") %> prohibited this cannabi from being saved:</h2>

      <ul>
      <% @cannabi.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :sativa %><br>
    <%= f.text_field :sativa %>
  </div>
  <div class="field">
    <%= f.label :indica %><br>
    <%= f.text_field :indica %>
  </div>
  <div class="field">
    <%= f.label :interior %><br>
    <%= f.text_field :interior %>
  </div>
  <div class="field">
    <%= f.label :exterior %><br>
    <%= f.text_field :exterior %>
  </div>
  <div class="field">
    <%= f.label :usuario_id %><br>
    <%= f.select("usuario_id",Usuario.all.collect{|l|[l.nombre, l.id] }, {include_black: 'seleccione usuario' })%>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>


<% end %>

app/views/cannabis/edit.html.erb
<h1>Editing Cannabi</h1>

<%= render 'form' %>

<%= link_to 'Show', @cannabi %> |
<%= link_to 'Back', cannabis_path %>

app/views/cannabis/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Cannabis</h1>

<table>
  <thead>
    <tr>
      <th>Sativa</th>
      <th>Indica</th>
      <th>Interior</th>
      <th>Exterior</th>
      <th>Usuario</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cannabis.each do |cannabi| %>
      <tr>
        <td><%= cannabi.sativa %></td>
        <td><%= cannabi.indica %></td>
        <td><%= cannabi.interior %></td>
        <td><%= cannabi.exterior %></td>
        <td><%= cannabi.usuario.nombre %></td>
        <td><%= link_to 'Show', cannabi %></td>
        <td><%= link_to 'Edit', edit_cannabi_path(cannabi) %></td>
        <td><%= link_to 'Destroy', cannabi, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cannabi', new_cannabi_path %>

app/views/cannabis/new.html.erb
<h1>New Cannabi</h1>

<%= render 'form' %>

<%= link_to 'Back', cannabis_path %>

app/views/cannabis/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Sativa:</strong>
  <%= @cannabi.sativa %>
</p>

<p>
  <strong>Indica:</strong>
  <%= @cannabi.indica %>
</p>

<p>
  <strong>Interior:</strong>
  <%= @cannabi.interior %>
</p>

<p>
  <strong>Exterior:</strong>
  <%= @cannabi.exterior %>
</p>

<p>
  <strong>Usuario:</strong>
  <%= @cannabi.usuario.nombre %>
</p>

<%= link_to 'Edit', edit_cannabi_path(@cannabi) %> |
<%= link_to 'Back', cannabis_path %>

app/views/cargamenu/_alert.html.erb
<% if notice %>
<div class="alert alert-success alert-dismissible" role="alert">
  <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
  <%= notice %>
</div>
<% end %>
<% if alert %>
<div class="alert alert-danger alert-dismissible" role="alert">
  <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
  <%= alert %>
</div>
<% end %>

app/views/cargamenu/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%=root_path%>">Home</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <% if user_signed_in? %>
          <li><a href="<%= usuarios_path %>">Usuarios</a></li>
          <li><a href="<%= cannabis_path %>">Cannabis</a></li>

        <% end %>
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
        <li><a> <%= current_user.email %> </a></li>
        	<li><a href="<%= edit_user_registration_path(current_user) %>">Editar Perfil</a></li>
        	<li><a href="<%= destroy_user_session_path %>", data-method="delete">Cerrar Sesión</a></li>
        <% else %>
        	<li><a href="<%= new_user_session_path %>">Iniciar Sesión</a></li>
        	<li><a href="<%= new_user_registration_path %>">Registrarse</a></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<!-- Latest compiled and minified CSS --> <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css"> <!-- Optional theme --> <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css"> <!-- Latest compiled and minified JavaScript --> <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>

<body>

  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
<%= render 'cargamenu/navbar' %>
<%= render 'cargamenu/alert' %> 
<%= yield %>

</body>
</html>

app/views/usuarios/_form.html.erb
<%= form_for(@usuario) do |f| %>
  <% if @usuario.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@usuario.errors.count, "error") %> prohibited this usuario from being saved:</h2>

      <ul>
      <% @usuario.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br>
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :apellido %><br>
    <%= f.text_field :apellido %>
  </div>
  <div class="field">
    <%= f.label :fechaNacimiento %><br>
    <%= f.text_field :fechaNacimiento %>
  </div>
  <div class="field">
    <%= f.label :comuna %><br>
    <%= f.text_field :comuna %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/usuarios/edit.html.erb
<h1>Editing Usuario</h1>

<%= render 'form' %>

<%= link_to 'Show', @usuario %> |
<%= link_to 'Back', usuarios_path %>

app/views/usuarios/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Usuarios</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Apellido</th>
      <th>Fechanacimiento</th>
      <th>Comuna</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @usuarios.each do |usuario| %>
      <tr>
        <td><%= usuario.nombre %></td>
        <td><%= usuario.apellido %></td>
        <td><%= usuario.fechaNacimiento %></td>
        <td><%= usuario.comuna %></td>
        <td><%= link_to 'Show', usuario %></td>
        <td><%= link_to 'Edit', edit_usuario_path(usuario) %></td>
        <td><%= link_to 'Destroy', usuario, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Usuario', new_usuario_path %>

app/views/usuarios/new.html.erb
<h1>New Usuario</h1>

<%= render 'form' %>

<%= link_to 'Back', usuarios_path %>

app/views/usuarios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @usuario.nombre %>
</p>

<p>
  <strong>Apellido:</strong>
  <%= @usuario.apellido %>
</p>

<p>
  <strong>Fechanacimiento:</strong>
  <%= @usuario.fechaNacimiento %>
</p>

<p>
  <strong>Comuna:</strong>
  <%= @usuario.comuna %>
</p>

<%= link_to 'Edit', edit_usuario_path(@usuario) %> |
<%= link_to 'Back', usuarios_path %>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>